
export const kGXYL_TimeSync = 0x0C00;//同步时间
export const kGXYL_SOS = 0x0160;     //手机通知提醒
export const kGXYL_GetEQ = 0x0900;  //获取设备电量
export const kGXYL_GetTime = 0x0800;//获取设备时间
export const kGXYL_setPointer = 0x0C01;//石英时间校准
export const kGXYL_GetDeviceInfo = 0x0980;//获取设备信息
export const kGXYL_RealtimeIsOpen = 0x0120;//实时步数心率
export const kGXYL_LaserRegimenParameters = 0x0480;//设置激光疗程参数
export const kGXYL_LaserManuallyParameters = 0x0481;//设置激光手动输出参数
export const kGXYL_LaserManuallyPayParameters = 0x0482;//设置手动激光付费参数
export const kGXYL_LaserIsOpen = 0x0483;//设置开关激光输出
export const kGXYL_HRAutomaticallIsOpen = 0x04A0;//设置心率自动监测
export const kGXYL_HRManuallyIsOpen = 0x04A1;  //开关心率检测
export const kGXYL_GetLaserRegimenParameters = 0x0880;//获取激光疗程参数
export const kGXYL_GetLaserManuallyParameters = 0x0881;//获取激光手动参数
export const kGXYL_GetLaserRecording = 0x0886;//获取激光治疗记录
export const kGXYL_GetHRRecording = 0x08A2;//获取心率监测记录
export const kGXYL_GetMotionRecording = 0x08E0;//获取计步数据
export const kGXYL_RestoreFactorySettings = 0x0FE1;//恢复出厂状态
export const kGXYL_GetManuallyHRState = 0x08A1;//获取心率开关状态
export const kGXYL_GetAutoHRState = 0x08A0;//获取自动心率状态
export const kGXYL_GetManuallyLaserState = 0x0885;//获取激光开关状态
export const KGXYL_startDFU = 0x0FE0 ;//启动空中升级
export const kGXYL_SetlaserTreatmentStatus = 0x484;//设置激光疗程周期
export const kGXYL_GetlaserTreatmentStatus = 0x887;//获取激光疗程周期
export const kGXYL_setNewPointer = 0x0c02; //06x指针调整
export const kGXYL_SetBoardCastDuration = 0x5A0;//设置蓝牙广播时长
export const kGXYL_GetBoardCastDuration = 0x9A0;//获取蓝牙广播时长
export const kGXYL_setLaserRegimen = 0x485; //设置激光疗程开启暂停